# Generated by Django 3.0.11 on 2021-06-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeriaapp', '0002_auto_20210613_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='precio',
            new_name='precio_familiar',
        ),
        migrations.AddField(
            model_name='pizza',
            name='precio_individual',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='pizza',
            name='precio_mediana',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
